name: Build and push ffmpeg-py image

on:
  workflow_dispatch:    # 手动触发
  push:                 # 每次 Dockerfile 变动也触发
    paths:
      - 'Dockerfile'
      - 'requirements.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # 关键：允许写 GHCR
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  # 自动生成，无需手动配置

      - name: Build & push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/ffmpeg-py:3.11
          cache-from: type=gha   # 使用 GitHub Actions 缓存
          cache-to:   type=gha,mode=max